### ISSUE TITLE
Task 2

### ISSUE THREAD

**Issue by sjiang1** [grandfoosier/EMUresearch#1]
(1) add a comment in that python file to explain the input arguments for your python program

(2) In the email, I sent you a project list of the 1000 most popular python projects in GitHub. This task is to modify your python program to automatically detect python files in the project and then extract all the methods from the python files.

Please create an ID for each method (then used as the filename for that method). You should keep (create/maintain) an ID file for methods. For each method,  the ID file should include the method's ID, the method's file location and the method's name.

Comment below for any questions.

**Comment by grandfoosier** [comment]
I've run into two main issues:
1. If I temporarily remove the import lines from the file, the import into my program will often still fail because it will reference something that doesn't exist. I have not found a way to either import and ignore the exception, or to get around the import altogether.
2. I have not been able to extract the methods from inside a class.

**Comment by sjiang1** [comment]
Kind of busy these two days. Will try to reply to you about these problems by Friday.

**Comment by sjiang1** [comment]
I did some digging and found an API that may work for us.

1. install _redbaron_ through pip
2. read: [the redbaron doc](https://redbaron.readthedocs.io/en/latest/tuto.htm) from beginning to learn this API
3. check out the following two code snippets for an example (in test.py, I used _.find_ method. You will need to use [.findAll](https://redbaron.readthedocs.io/en/latest/querying.html#find)) If you are not familiar with AST concept, it may be difficult to understand. But I think [the document](https://redbaron.readthedocs.io/en/latest/tuto.htm) is good enough, feel free to ask if you encounter any problem.

test.py
```
from redbaron import RedBaron
def main():
    with open("testcode.py", "r") as source_code:
        red = RedBaron(source_code.read())
        # print(red.help()) ## try this to see the data structure of 'red'
        defNode = red.find('DefNode');
        # print(defNode.help()) ## try this to see the data structure of 'defNode'
        print(defNode.dumps())

if __name__ == "__main__":
    main()
```
testcode.py # the source code that's being analyzed by _test.py_
```
import torch
from jiang import siyuan

class Trainer:
    def change_lr(self, new_lr):
        # add some comments
        for param_group in self.optimizer.param_groups:
            param_group['lr'] = new_lr

    def save(self, filename):
        savedict = {
                   'model': self.model.state_dict(), ## lalala
                   'optimizer': self.optimizer.state_dict()
                   }
        torch.save(savedict, filename)

    def load(self, filename):
        savedict = torch.load(filename, lambda storage, loc: storage)

        self.model.load_state_dict(savedict['model'])
        if self.args['mode'] == 'train':
            self.optimizer.load_state_dict(savedict['optimizer'])
```

**Comment by grandfoosier** [comment]
OK it seems like red_baron has an error in it somewhere. I think I got it working by editing the red_baron files, but who knows if that'll cause more problems down the line.

FYI:
In redbaron\base_nodes.py
I changed 

    def from_fst(klass, node_list, parent=None, on_attribute=None):
        return klass(map(lambda x: Node.from_fst(x, parent=parent, on_attribute=on_attribute), node_list), parent=parent, on_attribute=on_attribute)

at line 333 to

    def from_fst(klass, node_list, parent=None, on_attribute=None):
        try:
            return klass(map(lambda x: Node.from_fst(x, parent=parent, on_attribute=on_attribute), node_list),
                     parent=parent, on_attribute=on_attribute)
        except:
            return klass(map(lambda x: Node.from_fst(x, parent=parent, on_attribute=on_attribute), node_list[0]),
                     parent=parent, on_attribute=on_attribute)

**Comment by sjiang1** [comment]
Please log the error case here: which input you have, what version of red baron you are using, and the error message you got. So that I can reproduce the bug at my end.

**Comment by grandfoosier** [comment]
You can use your test.py file, but use it on call_center.py (which I just pushed) instead of testcode.py.
My red baron package is 0.9.2, which I believe is the latest version.
Here is the error message:

Traceback (most recent call last):
  File "test.py", line 11, in <module>
    main()
  File "test.py", line 4, in main
    red = RedBaron(source_code.read())
  File "C:\Users\rices\AppData\Local\Programs\Python\Python37-32\lib\site-packages\redbaron\redbaron.py", line 36, in __init__
    self.node_list = base_nodes.NodeList.from_fst(baron.parse(source_code), parent=self, on_attribute="root")
  File "C:\Users\rices\AppData\Local\Programs\Python\Python37-32\lib\site-packages\redbaron\base_nodes.py", line 335, in from_fst
    parent=parent, on_attribute=on_attribute)
  File "C:\Users\rices\AppData\Local\Programs\Python\Python37-32\lib\site-packages\redbaron\base_nodes.py", line 328, in __init__
    super(NodeList, self).__init__(initlist)
  File "C:\Users\rices\AppData\Local\Programs\Python\Python37-32\lib\collections\__init__.py", line 1073, in __init__
    self.data = list(initlist)
  File "C:\Users\rices\AppData\Local\Programs\Python\Python37-32\lib\site-packages\redbaron\base_nodes.py", line 334, in <lambda>
    return klass(map(lambda x: Node.from_fst(x, parent=parent, on_attribute=on_attribute), node_list),
  File "C:\Users\rices\AppData\Local\Programs\Python\Python37-32\lib\site-packages\redbaron\base_nodes.py", line 530, in from_fst
    return getattr(redbaron.nodes, class_name)(node, parent=parent, on_attribute=on_attribute)
  File "C:\Users\rices\AppData\Local\Programs\Python\Python37-32\lib\site-packages\redbaron\base_nodes.py", line 519, in __init__
    setattr(self, key, NodeList.from_fst(fst[key], parent=self, on_attribute=key))
  File "C:\Users\rices\AppData\Local\Programs\Python\Python37-32\lib\site-packages\redbaron\base_nodes.py", line 335, in from_fst
    parent=parent, on_attribute=on_attribute)
  File "C:\Users\rices\AppData\Local\Programs\Python\Python37-32\lib\site-packages\redbaron\base_nodes.py", line 328, in __init__
    super(NodeList, self).__init__(initlist)
  File "C:\Users\rices\AppData\Local\Programs\Python\Python37-32\lib\collections\__init__.py", line 1073, in __init__
    self.data = list(initlist)
  File "C:\Users\rices\AppData\Local\Programs\Python\Python37-32\lib\site-packages\redbaron\base_nodes.py", line 334, in <lambda>
    return klass(map(lambda x: Node.from_fst(x, parent=parent, on_attribute=on_attribute), node_list),
  File "C:\Users\rices\AppData\Local\Programs\Python\Python37-32\lib\site-packages\redbaron\base_nodes.py", line 529, in from_fst
    class_name = baron_type_to_redbaron_classname(node["type"])
TypeError: list indices must be integers or slices, not str

Once I dug into it, at one point some [[{....}]] was being passed to a function instead of [{....}].

**Comment by sjiang1** [comment]
I think you forgot to push :-)
-- I think I found it: https://raw.githubusercontent.com/donnemartin/system-design-primer/master/solutions/object_oriented_design/call_center/call_center.py
It is this one?
-- Ignore me. I reproduced the error. And will just double-check about it.

**Comment by grandfoosier** [comment]
You're right, sorry. Pushed now

**Comment by sjiang1** [comment]
I think the problem is with `metadata=ABCMeta`:
if we change `class Employee(metaclass=ABCMeta):`
to 
```
class Employee(object):
    __metaclass__ = ABCMeta
````
there is no error.

Your fix seems ok (hopefully). Use _submodules_ to add [redbaron reporsitory](https://github.com/PyCQA/redbaron) into our repository, and track your fix in redbaron in our submodule. If you would like, submit an issue stating this bug report in redbaron's repository to see if we can get a response.

Good job. Because of the time limit, we can't perfectly make a fix to a project we don't really know...

**Comment by grandfoosier** [comment]
I'm not familiar with submodules. I tried to add redbaron but I'm getting an error:

PS C:\Users\rices\documents\research> git submodule add git@github.com:PyCQA/redbaron redbaron
Cloning into 'C:/Users/rices/documents/research/redbaron'...
The authenticity of host 'github.com (192.30.253.113)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.253.113' (RSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:PyCQA/redbaron' into submodule path 'C:/Users/rices/documents/research/redbaron' failed

**Comment by sjiang1** [comment]
I will do the submodule then. You can try to run the code on other python files/projects to see if redbaron have more problems. If (magically) there seem to be no problem, you can continue working on this task then.

**Comment by sjiang1** [comment]
I have added the submodule to this repository (`libs/redbaron`).
You should try to modify the code in EMUresearch, so that we are using `libs/redbaron` instead of the pip installed package.

To modify redbaron, you can clone and push changes to the repo: `https://github.com/sjiang1/redbaron.git`

Then, to update the local copy of redbaron in `EMUresearch`, go to `EMUresearch/libs/redbaron`, do: `git pull`

I think the problem with your command of git submodule is using the ssh to clone. You can use https clone address instead. (I always use ssh, so the link I gave you is ssh..)
```
git submodule add https://github.com/PyCQA/redbaron
```

**Comment by sjiang1** [comment]
Oh, by the way, I put a issue in the official redbaron repository so we can track our changes.
https://github.com/PyCQA/redbaron/issues/192

**Comment by grandfoosier** [comment]
I believe I am finished with task 2. parseTop1000.py will iterate through the list, calling findPyFiles.py to open each project and extract its .py files.

Let me know if you would like me to change how I'm naming the files, though.
Currently I am saving them as

out/github_path/original_file_name[class_if_it_exists~inner_class_if_it_exists~method_name.py

paths.txt retains this information, split up like

original_file_name[(classes~)method_name.py      :  out/github_path

**Comment by grandfoosier** [comment]
hmm, apparently two tildes means strike-out. the name is

....[class(tilde)class(tilde)method.py

**Comment by sjiang1** [comment]
Got it. I will run your code at my end, and see if I need any change. Thanks!

**Comment by sjiang1** [comment]
I think extractMethods.py is still using "src/teatcode.py" as the input. Would you push your latest extractMethods.py to the repo?

**Comment by grandfoosier** [comment]
extractMethods is set to that as default for when it's run by itself. When it's called by findPyFiles it still uses the correct inputs. I changed the default though and pushed.

**Comment by sjiang1** [comment]
You are right. Running it now 👍
